/*
 * Java domain class for entity "Employee" 
 * Created on 2024-05-14 ( Date ISO 2024-05-14 - Time 18:11:42 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.example.demo.repositories;
import com.example.demo.entities.Employee;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
 * <h2>EmployeeRepository</h2>
 *
 * createdAt : 2024-05-14 - Time 18:11:42
 * <p>
 * Description: Spring Data repository for the {@link Employee} entity.
 * 
 * @author aek
 */
@Repository
public interface EmployeeRepository  extends JpaRepository<Employee, Integer> , JpaSpecificationExecutor<Employee> {

}
