name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '1.8'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: SonarQube Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn sonar:sonar \
        -Dsonar.projectKey=your_project_key \
        -Dsonar.host.url=http://localhost:9000 \
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}
