/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-05-14 ( Date ISO 2024-05-14 - Time 18:11:42 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.example.demo.controller;

import com.example.demo.entities.Employee;
import com.example.demo.service.EmployeeService;


import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.List;


/**
 * REST controller for managing {@link Employee}.
 *
 * @author @aek
 */
@RestController
@RequestMapping("/api/employee")
public class EmployeeController {

    private final Logger log = LoggerFactory.getLogger(EmployeeController.class);
	
    private final EmployeeService entityService;

 	public EmployeeController (EmployeeService entityService) {
		this.entityService = entityService;
	}

    /**
     * {@code POST  /employee} : Create a new employee.
     *
     * @param employee the employee to create.
     * @return the {@link ResponseEntity} with status {@code 201 (Created)} and with body the new employee.
     */
	@PostMapping()
	public ResponseEntity<Employee> createEmployee(@RequestBody @Validated Employee employee) {
         log.debug("REST request to save Employee : {}", employee);
         return new ResponseEntity<>(entityService.create(employee), HttpStatus.CREATED);
    }

   /**
     * {@code PUT  /employee} : Updates an existing employee.
     *
     * @param employee the employee to update.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the updated employee,
     * or with status {@code 400 (Bad Request)} if the employee is not valid,
     * or with status {@code 500 (Internal Server Error)} if the employee couldn't be updated.
     */
    @PutMapping()
    public ResponseEntity<Employee> updateEmployee(@Validated @RequestBody Employee employee) {
        log.debug("REST request to update Employee : {}", employee);
        Employee result = entityService.update(employee);
        return ResponseEntity.ok().body(result);
    }

    /**
     * {@code GET  /employee} : get all the employees.
     *
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and the list of employee in body.
     */

    @GetMapping()
    public ResponseEntity<List<Employee>> getAllEmployee() {
	    log.debug("REST request to get all employees");
        List<Employee> lst = entityService.getAll();

        return new ResponseEntity<>(lst,HttpStatus.OK);
    }

    /**
     * {@code GET  /employee/:id} : get the "id" employee.
     *
     * @param id the id of the employee to retrieve.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the employee, or with status {@code 404 (Not Found)}.
     */
    @GetMapping(value = "/{id}")
    public ResponseEntity<Employee> getOneEmployee(@PathVariable("id") Integer id) {
        log.debug("REST request to get Employee : {}", id);
        Employee e = entityService.getOne(id);

        return new ResponseEntity<>(e, HttpStatus.OK);
    }

  /**
     * {@code DELETE  /employee/:id} : delete the "id" employee.
     *
     * @param id the id of the employee to delete.
     * @return the {@link ResponseEntity} with status {@code 204 (NO_CONTENT)}.
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteEmployee(@PathVariable("id") Integer id) {
        log.debug("REST request to delete Employee : {}", id);
        entityService.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }

//test

}
